<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"
          integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="css/styles.css">

    <title>Error</title>
</head>
<body>
    <p>
        Message:
        <?php echo $e->getMessage() ?>
    </p>


    <p>
        Code:
        <?php echo $e->getCode() ?>
    </p>

    <p>
        File name:
        <?php echo $e->getFile() ?>
    </p>
    <p>
        Line:
        <?php echo $e->getLine() ?>
    </p>
    <p>
        Trace:
        <?php echo $e->getTraceAsString() ?>
    </p>


    <p>
        <?php if (!is_null($e->getPrevious())): ?>
        Previous:


    <p>
        Message:
        <?php echo $e->getPrevious()->getMessage() ?>
    </p>


    <p>
        Code:
        <?php echo $e->getPrevious()->getCode() ?>
    </p>

    <p>
        File name:
        <?php echo $e->getPrevious()->getFile() ?>
    </p>
    <p>
        Line:
        <?php echo $e->getPrevious()->getLine() ?>
    </p>
    <p>
        Trace:
        <?php echo $e->getPrevious()->getTraceAsString() ?>
    </p>

    <?php endif ?>


</body>
</html>