<?php 
if (isset($_POST['regStudToPoint'])) {
	$errors = $currentUser->regToPoint($_GET['eventId'], $_POST['pointId']);

	if ( is_null( $errors ) )
		echo "Регистрация прошла успешно";
	else {
		foreach ($errors as $error) {
			echo "<p>";
			echo $error;
			echo "</p>";
		}
	}
}

if ( isset( $_POST['unregStudFromPoint'] ) ) {
	$errors = $currentUser->unregFromPoint($_GET['eventId'], $_POST['pointId']);
	
	if ( is_null( $errors ) )
		echo "Регистрация отменена";
	else {
		foreach ($errors as $error) {
			echo "<p>";
			echo $error;
			echo "</p>";
		}
	}
	
}



?>




<?php //require_once(INCLUDE_PATH . '/header.php'); ?>


<div class="container">
	<div class='reg-background'>

		<?php
		if ( !is_null( $currentUser ) ) {
			echo "<p>";
			$regedPoint = $currentUser->getRegedEventPoint($_GET['eventId']);
			if ( !is_null( $regedPoint ) )
				echo "Зарегистрирован на " . "<a href=''>" . $regedPoint->getName() . "</a>";
					// print_r($regedPoint->getName());
			else
				echo "Не зарегистрирован нигде";
			echo "</p>";
		}
		?>


		<?php if ( !is_null( $points ) ):
			foreach ( $points as $point ): ?>

				<div class="text-center py-5">
					<h1>
						<p>ID этапа: <?php echo $point->getId() ?></p>
					</h1>
					<h1>
						<p>ID мероприятия: <?php echo $point->getEventId() ?></p>
					</h1>	
					<h1>
						<p>Название: <?php echo $point->getName() ?> </p>
					</h1>
					<p>Описание: <?php echo $point->getDescription() ?> </p>				
				</div>

				<?php if ( !is_null( $currentUser ) ): ?>
					<form action="" method="post">
						<?php if ( !$currentUser->isRegedToPoint( $point->getEventId(), $point->getId() ) ): ?>
						<div class="text-center">
							<input type="hidden" name="pointId" value="<?php echo $point->getId() ?>">
							<button class="reg-button btn btn-primary btn-lg" name="regStudToPoint">Зарегистрироваться</button>
						</div>
						<?php else: ?>
							<div class="text-center">
								<input type="hidden" name="pointId" value="<?php echo $point->getId() ?>">
								<button class="reg-button btn btn-primary btn-lg" name="unregStudFromPoint">Отменить регистрацию</button>
							</div>
						<?php endif; ?>
					</form>
				<?php endif; ?>


				<?php
			endforeach; 
		endif;
		?>

	</div>
</div>

<?php //require_once('includes/footer.php') ?>
