<?php
//require_once('includes/header.php');
// require_once('config/db_connection.php');
?>

<div class="container">
    <div class='reg-background'>


        <div class="text-center">
            <h1> Мероприятия</h1>
        </div>

        <table class="event-table mt-5">
            <!--        <table class="table table-striped table-hover">-->
            <thead>
            <tr>
                <th>Название мероприятия</th>
                <th>Описание</th>
            </tr>
            </thead>
            <tbody>


            <?php
            if (!empty($events)) {
                foreach ($events as $event) {

                    ?>
                    <tr>
                        <td>
                            <a href="/view-event/?eventId=<?php echo $event->getId() ?> ">
                                <?php echo htmlspecialchars($event->getName()) ?> </a>
                        </td>
                        <td> <?php echo htmlspecialchars($event->getDescription()) ?> </td>
                    </tr>
                    <?php
                }
            }


            ?>

            </tbody>

        </table>
    </div>

</div>


<?php //require_once('includes/footer.php') ?>
